export const SET_EMAIL = 'SET_EMAIL';
export const SET_PASSWORD = 'SET_PASSWORD';
export const SET_LOGIN_ERROR = 'SET_LOGIN_ERROR';
export const TOGGLE_NEW_PASSWORD_FORM = 'TOGGLE_NEW_PASSWORD_FORM';
export const SET_AUTHENTICATED_USER = 'SET_AUTHENTICATED_USER';
export const SET_USER_ATTRIBUTES = 'SET_USER_ATTRIBUTES';
export const SET_IS_LOADING = 'SET_IS_LOADING';
export const SET_IS_PASSWORD_VISIBLE = 'SET_IS_PASSWORD_VISIBLE';
